export function initHud() {
  const elements = {
    elTime: document.getElementById("time"),
    elLvl: document.getElementById("lvl"),
    elKills: document.getElementById("kills"),
    elDps: document.getElementById("dps"),
    elWep: document.getElementById("wep"),
    elRerolls: document.getElementById("rerolls"),
    elThreat: document.getElementById("threat"),
    elActionHint: document.getElementById("actionHint"),
    elActiveItems: document.getElementById("activeItems"),
    elActiveItemsList: document.getElementById("activeItemsList"),
    elTotemTimer: document.getElementById("totemTimer"),
    elTotemWarning: document.getElementById("totemWarning"),
    elHpbar: document.getElementById("hpbar"),
    elHpbarPulse: document.getElementById("hpbarPulse"),
    elXpbar: document.getElementById("xpbar"),
    elHptext: document.getElementById("hptext"),
    elXptext: document.getElementById("xptext"),
    elTotemBar: document.getElementById("totemBar"),
    elTotemText: document.getElementById("totemText"),
    elBossBar: document.getElementById("bossBar"),
    elBossText: document.getElementById("bossText"),
    elChestBar: document.getElementById("chestBar"),
    elChestText: document.getElementById("chestText"),
    elBossWrap: document.getElementById("bossWrap"),
    elBossList: document.getElementById("bossList"),
  };
  return elements;
}
