export function initOverlays() {
  const elements = {
    mainMenuOverlay: document.getElementById("mainMenu"),
    btnFreePlay: document.getElementById("btnFreePlay"),
    btnMenuRecords: document.getElementById("btnMenuRecords"),
    btnMenuSettings: document.getElementById("btnMenuSettings"),
    startOverlay: document.getElementById("start"),
    charsWrap: document.getElementById("chars"),
    pickerOverlay: document.getElementById("picker"),
    pickerTitle: document.getElementById("pickerTitle"),
    pickerHint: document.getElementById("pickerHint"),
    choicesWrap: document.getElementById("choices"),
    btnReroll: document.getElementById("btnReroll"),
    btnSkip: document.getElementById("btnSkip"),
    btnShowBuild: document.getElementById("btnShowBuild"),
    pauseMenu: document.getElementById("pauseMenu"),
    buildListEl: document.getElementById("buildList"),
    invListEl: document.getElementById("invList"),
    tabUpgrades: document.getElementById("tabUpgrades"),
    tabInventory: document.getElementById("tabInventory"),
    buildStatsEl: document.getElementById("buildStats"),
    btnResume: document.getElementById("btnResume"),
    btnRestart2: document.getElementById("btnRestart2"),
    btnCopy: document.getElementById("btnCopy"),
    btnRecords: document.getElementById("btnRecords"),
    btnSettings: document.getElementById("btnSettings"),
    btnHang: document.getElementById("btnHang"),
    restartConfirmOverlay: document.getElementById("restartConfirm"),
    btnRestartYes: document.getElementById("btnRestartYes"),
    btnRestartNo: document.getElementById("btnRestartNo"),
    gameoverOverlay: document.getElementById("gameover"),
    summaryEl: document.getElementById("summary"),
    restartBtn: document.getElementById("restart"),
    copyBtn: document.getElementById("copyStats"),
    btnRecordsOver: document.getElementById("btnRecordsOver"),
    recordsOverlay: document.getElementById("records"),
    recordsListEl: document.getElementById("recordsList"),
    btnRecordsClose: document.getElementById("btnRecordsClose"),
    settingsOverlay: document.getElementById("settings"),
    btnSettingsClose: document.getElementById("btnSettingsClose"),
    optShowDamageNumbers: document.getElementById("optShowDamageNumbers"),
    optShowProfiler: document.getElementById("optShowProfiler"),
    btnPause: document.getElementById("btnPause"),
    actionBar: document.getElementById("actionBar"),
    actionBarFill: document.getElementById("actionBarFill"),
  };
  return elements;
}
